name = "cudatoolkit-repo"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "02f3740963833cd9735075c82bf68d9d"

[vars]
GITHUB_OWNER = "dfalbel"
GITHUB_REPO = "cudatoolkit"
GHPAGES_HOST = "dfalbel.github.io"
